/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Feed } from "./Feed";
import { FeedCountArgs } from "./FeedCountArgs";
import { FeedFindManyArgs } from "./FeedFindManyArgs";
import { FeedFindUniqueArgs } from "./FeedFindUniqueArgs";
import { CreateFeedArgs } from "./CreateFeedArgs";
import { UpdateFeedArgs } from "./UpdateFeedArgs";
import { DeleteFeedArgs } from "./DeleteFeedArgs";
import { User } from "../../user/base/User";
import { FeedService } from "../feed.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Feed)
export class FeedResolverBase {
  constructor(
    protected readonly service: FeedService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Feed",
    action: "read",
    possession: "any",
  })
  async _feedsMeta(
    @graphql.Args() args: FeedCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Feed])
  @nestAccessControl.UseRoles({
    resource: "Feed",
    action: "read",
    possession: "any",
  })
  async feeds(@graphql.Args() args: FeedFindManyArgs): Promise<Feed[]> {
    return this.service.feeds(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Feed, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Feed",
    action: "read",
    possession: "own",
  })
  async feed(@graphql.Args() args: FeedFindUniqueArgs): Promise<Feed | null> {
    const result = await this.service.feed(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Feed)
  @nestAccessControl.UseRoles({
    resource: "Feed",
    action: "create",
    possession: "any",
  })
  async createFeed(@graphql.Args() args: CreateFeedArgs): Promise<Feed> {
    return await this.service.createFeed({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Feed)
  @nestAccessControl.UseRoles({
    resource: "Feed",
    action: "update",
    possession: "any",
  })
  async updateFeed(@graphql.Args() args: UpdateFeedArgs): Promise<Feed | null> {
    try {
      return await this.service.updateFeed({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Feed)
  @nestAccessControl.UseRoles({
    resource: "Feed",
    action: "delete",
    possession: "any",
  })
  async deleteFeed(@graphql.Args() args: DeleteFeedArgs): Promise<Feed | null> {
    try {
      return await this.service.deleteFeed(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Feed): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
